[package]
name = "USDC"
version = "0.1.0"
published-at = "0x0" # Will be updated automatically after publishing

[dependencies]
# Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
# If you need to depend on the bridge package, uncomment the line below and update the address
# Bridge = { local = "../../bridge" }

[addresses]
USDC = "0x0" # Will be updated automatically after publishing
